// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDzvrW4u4XfUFvmvnd8EZlzNlgoGWubW0',
    appId: '1:602371344297:web:f2f6ae1d774f90dfa126b8',
    messagingSenderId: '602371344297',
    projectId: 'food-delivery-app-6954f',
    authDomain: 'food-delivery-app-6954f.firebaseapp.com',
    storageBucket: 'food-delivery-app-6954f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNZvCHs51R68MauXiDgBV8fVBa1eWLzo',
    appId: '1:602371344297:android:495b230b6035fd7fa126b8',
    messagingSenderId: '602371344297',
    projectId: 'food-delivery-app-6954f',
    storageBucket: 'food-delivery-app-6954f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEXiICwO8uv9Z6MKLcTLfOFBRBHUTHW-o',
    appId: '1:602371344297:ios:27228a6e4a3b91c9a126b8',
    messagingSenderId: '602371344297',
    projectId: 'food-delivery-app-6954f',
    storageBucket: 'food-delivery-app-6954f.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEXiICwO8uv9Z6MKLcTLfOFBRBHUTHW-o',
    appId: '1:602371344297:ios:27228a6e4a3b91c9a126b8',
    messagingSenderId: '602371344297',
    projectId: 'food-delivery-app-6954f',
    storageBucket: 'food-delivery-app-6954f.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDzvrW4u4XfUFvmvnd8EZlzNlgoGWubW0',
    appId: '1:602371344297:web:f784e17c9e057858a126b8',
    messagingSenderId: '602371344297',
    projectId: 'food-delivery-app-6954f',
    authDomain: 'food-delivery-app-6954f.firebaseapp.com',
    storageBucket: 'food-delivery-app-6954f.firebasestorage.app',
  );

}